//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookClient.PhoneBookService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneBookService.IPhoneBookService")]
    public interface IPhoneBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneBookService/AddEntry", ReplyAction="http://tempuri.org/IPhoneBookService/AddEntryResponse")]
        [System.ServiceModel.Web.WebGet(UriTemplate = "/AddEntry/{lastName},{firstName},{phoneNumber}", BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        string AddEntry(string lastName, string firstName, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneBookService/AddEntry", ReplyAction="http://tempuri.org/IPhoneBookService/AddEntryResponse")]
        System.Threading.Tasks.Task<string> AddEntryAsync(string lastName, string firstName, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneBookService/GetEntries", ReplyAction="http://tempuri.org/IPhoneBookService/GetEntriesResponse")]
        [System.ServiceModel.Web.WebGet(UriTemplate = "/GetEntries/{lastName}", BodyStyle = System.ServiceModel.Web.WebMessageBodyStyle.Wrapped)]
        System.Collections.Generic.List<string> GetEntries(string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneBookService/GetEntries", ReplyAction="http://tempuri.org/IPhoneBookService/GetEntriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetEntriesAsync(string lastName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneBookServiceChannel : PhoneBookClient.PhoneBookService.IPhoneBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneBookServiceClient : System.ServiceModel.ClientBase<PhoneBookClient.PhoneBookService.IPhoneBookService>, PhoneBookClient.PhoneBookService.IPhoneBookService {
        
        public PhoneBookServiceClient() {
        }
        
        public PhoneBookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneBookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneBookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneBookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddEntry(string lastName, string firstName, string phoneNumber) {
            return base.Channel.AddEntry(lastName, firstName, phoneNumber);
        }
        
        public System.Threading.Tasks.Task<string> AddEntryAsync(string lastName, string firstName, string phoneNumber) {
            return base.Channel.AddEntryAsync(lastName, firstName, phoneNumber);
        }
        
        public System.Collections.Generic.List<string> GetEntries(string lastName) {
            return base.Channel.GetEntries(lastName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetEntriesAsync(string lastName) {
            return base.Channel.GetEntriesAsync(lastName);
        }
    }
}
